@id=62e12b9c7dab47ff50b99886
@host=http://localhost:3001


GET {{host}}

### Create a new activityListItem
POST {{host}}/activityList
Content-Type:application/json

[
{
    "starts_date": "2022-12-23T21:00:00Z",
    "ends_date":"2022-12-23T03:00:00Z",
    "title":"Prepare Dinner for Friday", 
    "description": "Also make shoppingList before",
    "tasks":[],    
    "contacts:":[],  
    "category":"Social events",
    "imgBackground_url":"https://media.istockphoto.com/photos/cozy-new-year-dinner-among-friends-picture-id1183637273?k=20&m=1183637273&s=170667a&w=0&h=URb5M-vdmaphOq8jh7GoXB7BpPFGRMn0IaitLC_DhYQ="
},
{
    "starts_date": "2022-12-14T10:00:00Z",
    "ends_date":"2022-12-14T13:00:00Z",
    "title":"Cellar Clearance", 
    "description": "Get a car for bringing the rubbish to the recycling center",
    "tasks":[],    
    "contacts:":[],  
    "category":"ToDos",
    "imgBackground_url":"https://aflex.berlin/wp-content/uploads/2021/01/k.jpg"
},
{
    "starts_date": "2022-12-23T21:00:00Z",
    "ends_date":"2022-12-23T03:00:00Z",
    "title":"Prepare Dinner for Friday", 
    "description": "Also make shoppingList before",
    "calenderItem":[],    
    "tasks:":[],  
    "category":"Social events",
    "imgBackground_url":"https://media.istockphoto.com/photos/cozy-new-year-dinner-among-friends-picture-id1183637273?k=20&m=1183637273&s=170667a&w=0&h=URb5M-vdmaphOq8jh7GoXB7BpPFGRMn0IaitLC_DhYQ="
},
{
    "starts_date": "2022-12-03T21:00:00.000Z",
    "ends_date": "2022-12-04T03:00:00.000Z",
    "title": "Cleanning the house",
    "description": "nothing",
    "tasks": [],
    "contacts": [],
    "category": "ToDos",
    "imgBackground_url": "https://housewifehowtos.com/wp-content/uploads/2021/04/Games-that-Get-Kids-to-Help-Clean-House.jpeg"
}
]

### Add an Item to a List
PATCH {{host}}/activityList/addTasks 
Content-Type: application/json

[
{"listId": "62e12b9c7dab47ff50b99886", "taskId": 
    [
    "62e129d3a1b07c906e90319a","62e129d3a1b07c906e90319b", "62e129d3a1b07c906e90319d",
    "62e129d3a1b07c906e903198","62e129d3a1b07c906e903199", "62e129d3a1b07c906e90319c"    
    ]
}
]
### Get all activityListItems
GET {{host}}/activityList

### Get one activityListItem by id
GET {{host}}/activityList/{{id}}

### Patch one activityListItem
PATCH {{host}}/activityList/{{id}}
Content-Type:application/json

{
   "key":"description",
   "value":"Nothing to add here"
}

### UPDATE one Item
PUT {{host}}/activityList/{{id}}
Content-Type:application/json

{
    "starts_date":"2022-12-03T21:00:00.000Z",
    "description":"All fine"   
}

### Delete
DELETE {{host}}/activityList/{{id}}

### Delete many --> "category":"sports"
DELETE {{host}}/activityList
Content-Type:application/json

{
   "key":"category",
   "value":"Social events"
}

### Delete All cactivityListItems
DELETE {{host}}/activityList/deleteAll