@id=62e128e3e713fa9988f9865e
@host=http://localhost:3031
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmYyOTg1MzhkODMyZTQ3YmI2YTNhZGEiLCJ1c2VyRW1haWwiOiJndXNvMjJAaG90bWFpbC5jb20iLCJpYXQiOjE2NjAwNjg1MzMsImV4cCI6MTY2MDE1NDkzM30.Ib-Fm8ClcXbKLEdSsOx3J0aPVcuZ_TYzlI2pPwd_IzM


GET {{host}}

### Create new calenderItems
POST {{host}}/calendar
Content-Type:application/json
Authorization: bearer {{token}}

[
    {
        "end":"2022-12-04T03:00:00Z",
        "start": "2022-12-03T21:00:00Z",        
        "title":"Lunch with my Friends for celebrating Christmas in the mexican Restautant", 
        "description": "Ask before if they have also Vegan meals",
        "activityList":[],    
        "contacts":[],  
        "category":"Birthdays",
        "img_url":"https://popmenucloud.com/xrpblwcd/85ba676e-8969-4793-ba64-46c7724547be.jpg"
    },
    {
        "start": "2022-12-05T18:00:00Z",
        "end":"2022-12-05T19:00:00Z",
        "title":"Meeting for running with Patrick", 
        "description": "training in the Park",
        "activityList":[],    
        "contacts":[],  
        "category":"Birthdays",
        "img_url":"https://img.theculturetrip.com/1440x/smart/wp-content/uploads/2018/11/p9k2ym.jpg"
    },
    {
        "start": "2022-12-03T21:00:00Z",
        "end":"2022-12-04T03:00:00Z",
        "title":"Thai massage Meeting", 
        "description": "Made an appointment and paid the half in advance",
        "activityList":[],    
        "contacts":[],  
        "category":"Personal",
        "img_url":"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/66/73/79/sawasdeeka-thai-massage.jpg?w=1200&h=1200&s=1"
    }
]

### Add contacts to a calenderItem
PATCH {{host}}/calender/addContacts
Content-Type: application/json

[
    {"calenderItemId": "62e128e3e713fa9988f9865e", "contactsId": 
        [ "62e13d07dc4d17aa1a5c5dbe","62e13d07dc4d17aa1a5c5dbf", "62e13d07dc4d17aa1a5c5dc0"]
    }
]

### Add activityList to a calenderItem
PATCH {{host}}/calender/addActivityList
Content-Type: application/json

[
    {"calenderItemId": "62e128e3e713fa9988f9865e", "activityListId": 
        [ "62e129aba1b07c906e903191","62e129aba1b07c906e903190", "62e12b9c7dab47ff50b99886"]
    }
]



### Get all calenderItems
GET {{host}}/calendar/
Authorization: bearer {{token}}

### Get all birthdays
GET {{host}}/calendar/birthdays/
Authorization: bearer {{token}}

### Get one calenderItem by id
GET {{host}}/calendar/{{id}}

### Patch one calenderItem
PATCH {{host}}/calendar/{{id}}
Content-Type:application/json

{
   "key":"description",
   "value":"Paid nothing in advance"
}

### UPDATE one Item
PUT {{host}}/calender/{{id}}
Content-Type:application/json

{
    "starts_date":"2022-12-11T18:00:00.000Z",
    "description":"Paid all of it in advance"   
}

### Delete
DELETE {{host}}/calender/{{id}}

### Delete many --> "category":"sports"
DELETE {{host}}/calender
Content-Type:application/json

{
   "key":"category",
   "value":"Sports"
}

### Delete All ccalenderItems
DELETE {{host}}/calendar/deleteAll